# fly.toml app configuration file generated for create-fly-backend on 2025-04-09T22:13:11-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'create-fly-backend'
primary_region = 'ewr'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8080'

[[mounts]]
  source = 'create_data'
  destination = '/data'

[[services]]
  protocol = 'tcp'
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']
    
  [[services.http_checks]]
    interval = 10000
    grace_period = '5s'
    method = 'get'
    path = '/api/health'
    protocol = 'http'
    timeout = 2000

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = 'connections'

  [[services.http_options]]
    response_headers = { 'Access-Control-Allow-Origin' = '*', 'Access-Control-Allow-Methods' = 'GET, POST, PUT, DELETE, OPTIONS', 'Access-Control-Allow-Headers' = 'Content-Type, Authorization, X-Requested-With, Accept', 'Access-Control-Allow-Credentials' = 'true', 'Cross-Origin-Resource-Policy' = 'cross-origin', 'Cross-Origin-Embedder-Policy' = 'credentialless', 'Cross-Origin-Opener-Policy' = 'same-origin' }

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
